defaults:
  - process: process1
  - model: model1
  - _self_


reports:
  dir: reports
  figures_dir: reports/figures


################################ PATHS ################################
external:
  dir: data/external
  name: external.csv
  path: ${external.dir}/${external.name}

raw: 
  paths:
    - data/raw/427929.root

interim:
  dir: data/interim
  name: interim.csv
  path: ${interim.dir}/${interim.name}

processed:
  dir: data/processed
  name: processed.csv
  path: ${processed.dir}/${processed.name}

################################

model_dir: models

######################################################################